"""Fix User columns

Revision ID: 0fd9708cf37b
Revises: 4515f29ca704
Create Date: 2025-12-19 01:07:24.412074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fd9708cf37b'
down_revision = '4515f29ca704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('cart_history', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('cart_history', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
